# Generated by Django 5.1.7 on 2025-03-28 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('casino', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='saldo',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=10),
        ),
    ]
